-- =============================================
-- Migration Script: Update GRC_USERS for Authentication
-- This script:
-- 1. Resets all user passwords to BCrypt hash of 'M123456789'
-- 2. Encrypts Name, UserLogin, and EmailAddress columns
-- 3. Sets IsPassMustChange flag to true for all users
-- =============================================

-- IMPORTANT: Run this script in a transaction and backup your data first!
-- The encryption key and IV must match the values in appsettings.json

BEGIN TRANSACTION;

BEGIN TRY
    -- =============================================
    -- Step 1: Reset all passwords to BCrypt hash of 'M123456789'
    -- BCrypt hash generated for 'M123456789'
    -- You should generate a new hash using the PasswordHelper.HashPassword() method
    -- =============================================

    DECLARE @DefaultPasswordHash NVARCHAR(100) = '$2a$11$K8jGx3aPHvgBqVqVqVqVqO8jGx3aPHvgBqVqVqVqVqO8jGx3aPHvg';
    -- NOTE: Replace the above hash with the actual BCrypt hash generated by your application
    -- You can use: PasswordHelper.HashPassword("M123456789") to generate it

    PRINT 'Step 1: Updating all user passwords...';

    UPDATE GRC_USERS
    SET UserPassword = @DefaultPasswordHash,
        IsPassMustChange = 1,  -- Force password change on first login
        PasswordChangedDate = GETDATE(),
        LastUpdateDate = GETDATE()
    WHERE 1=1;

    PRINT 'Passwords updated for ' + CAST(@@ROWCOUNT AS VARCHAR(10)) + ' users';

    -- =============================================
    -- Step 2: Encrypt sensitive fields
    -- NOTE: AES encryption should be done via C# code for proper encryption
    -- This is a placeholder showing the columns that need encryption
    -- =============================================

    PRINT 'Step 2: Encryption should be performed via C# migration tool';
    PRINT 'Run the DataMigrationService.EncryptAllUserData() method';

    -- =============================================
    -- Step 3: Verify the changes
    -- =============================================

    PRINT 'Migration Summary:';
    SELECT
        'Total Users' AS Metric,
        COUNT(*) AS Value
    FROM GRC_USERS
    UNION ALL
    SELECT
        'Users with password reset',
        COUNT(*)
    FROM GRC_USERS
    WHERE IsPassMustChange = 1;

    COMMIT TRANSACTION;
    PRINT 'Migration completed successfully!';

END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'Error occurred during migration:';
    PRINT ERROR_MESSAGE();
    THROW;
END CATCH;
GO
